apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template
  title: Component Template
  description: Call an api
  tags:
    - api
spec:
  owner: platform
  type: component

  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties:
       repoUrl:
         title: Repository Location
         type: string
         ui:field: RepoUrlPicker
         ui:options:
           allowedHosts:
             - dev.azure.com        
           requestUserCredentials:
             secretsKey: USER_OAUTH_TOKEN
             additionalScopes:
               azure: []

  steps:
    - id: call
      name: call api
      action: alsenseavdgroup:call-api
      input:
        displayName: "testsjh"
        mailNickname: "testsjh"

  output:
    text:
      - title: Result
        content: |
          **Result:** `${{ steps['call'].output.result }}`
